################ Edit lines below #################

PREFIX=/usr/local/weibo_socket
SBINDIR=$(PREFIX)/sbin
LIBDIR=$(PREFIX)/lib
HEADERDIR=$(PREFIX)/include
CONFDIR=$(PREFIX)/conf
LOGDIR=$(PREFIX)/log
 
PREFIX_LIBWIEBOSOCKET_PROTOCOL=/usr/local/weibo_socket
LIBDIR_LIBWIEBOSOCKET_PROTOCOL=$(PREFIX_LIBWIEBOSOCKET_PROTOCOL)/lib
HEADERDIR_LIBWIEBOSOCKET_PROTOCOL=$(PREFIX_LIBWIEBOSOCKET_PROTOCOL)/include

INSTALL=install

################ DON'T Edit lines below #################

APPNAME=weibo_socket
APPVERSION_MAJ=0
APPVERSION_MIN=1

CFLAGS+=-DAPPNAME=\"$(APPNAME)\" -DAPPVERSION_MAJ=\"$(APPVERSION_MAJ)\" -DAPPVERSION_MIN=\"$(APPVERSION_MIN)\" -DCONFDIR=\"$(CONFDIR)\" -DINSTALL_PREFIX=\"$(PREFIX)\" -I$(HEADERDIR) -I$(HEADERDIR_LIBWIEBOSOCKET_PROTOCOL)
LDFLAGS+=-L$(LIBDIR) -L$(LIBDIR_LIBWIEBOSOCKET_PROTOCOL)
