PREFIX=/usr/local/weibo_socket
LIBDIR=$(PREFIX)/lib
INCDIR=$(PREFIX)/include

PREFIX_LIBWSOCKET_PROTOCOL=/usr/local/weibo_socket
LIBDIR_LIBWSOCKET_PROTOCOL=$(PREFIX_LIBWSOCKET_PROTOCOL)/lib
INCDIR_LIBWSOCKET_PROTOCOL=$(PREFIX_LIBWSOCKET_PROTOCOL)/include

INSTALL=install

